Jacoco setup
android-playa-kotlinita/Herbiary pull request #19
Opened 2022-06-07 19:55 UTC by josamtzc

Jacoco setup

## Affected files
app/build.gradle.kts
kotlin/com.apk.herbiary.library.jacoco.gradle.kts
kotlin/com.apk.herbiary.application.jacoco.gradle.kts
herbiary/Jacoco.kt

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review (can be ignored)
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2022-06-08 17:30 UTC, mayteCabral requested changes

2022-06-08 17:30 UTC, mayteCabral commented on gradle/build-logic/convention/src/main/kotlin/com/apk/herbiary/Jacoco.kt
> +        //val coverageTaskName = "create${variant.name.capitalize()}CoverageReport"
dejaste un comentario aqui, puedes removerlo plis

2022-06-08 23:06 UTC, mayteCabral approved these changes

2022-06-16 18:35 UTC, os-wize approved these changes

2022-06-16 18:35 UTC, merged