Splash Screen UI
android-playa-kotlinita/Herbiary pull request #35
Opened 2022-06-25 03:13 UTC by an-lopez

## Describe your changes
Added UI for Splash screen

## Affected files
SplashScreen.kt

## Type of change
Added new screen

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review (can be ignored)
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2022-06-29 16:11 UTC, os-wize approved these changes

2022-06-29 16:23 UTC, mayteCabral requested changes

2022-06-29 16:23 UTC, mayteCabral commented on app/src/main/java/com/apk/herbiary/screens/splash/SplashScreen.kt
> +        text = "Splash Screen",
this should be in the strings.xml :)

2022-06-29 16:23 UTC, mayteCabral commented on feature-authentication/src/main/java/com/apk/herbiary/screens/login/ForgotPasswordScreen.kt
> +                .padding(horizontal = 24.dp)
dimens file 😢

2022-06-29 16:23 UTC, mayteCabral commented on feature-authentication/src/main/java/com/apk/herbiary/screens/login/LoginScreen.kt
> +            Button(
Maybe doing only one button component with our own styles should be better so this part is shorter and can be used in all the application

2022-06-29 16:23 UTC, mayteCabral commented on feature-authentication/src/main/java/com/apk/herbiary/screens/login/ui/GoogleSignInButton.kt
> +fun GoogleSignInButton(onClick: () -> Unit){
Maybe instead of using multiple button components we can make only one with all the stuff we need, we can check this later

2022-07-05 23:03 UTC, DiegoMedinaP approved these changes

2022-07-05 23:59 UTC, closed without merging